import React from "react";
import { API_URL } from "../config.js";
import { useLanguage } from "../i18n.jsx";
import {
  Activity,
  Download,
} from "lucide-react";

export function ReportActions() {
  const { t } = useLanguage();
  async function downloadSummaryPdf() {
    const response = await fetch(`${API_URL}/reports/executive-summary`);
    const data = await response.json();
    const impact = data.queue_impact || {};
    const impactHtml = impact.baseline_wait_minutes !== undefined
      ? `
      <h2>Queue Optimization Impact (Case 1)</h2>
      <p>Baseline (all trucks at peak): <b>${impact.baseline_queue_trucks} trucks, ${impact.baseline_wait_minutes} min wait</b> (p95 ${impact.baseline_p95_minutes} min)</p>
      <p>With staggered dispatch: <b>${impact.optimized_queue_trucks} trucks, ${impact.optimized_wait_minutes} min wait</b> (p95 ${impact.optimized_p95_minutes} min)</p>
      <p>Queue wait reduction: <b>-${impact.queue_reduction_percent}%</b> (${impact.method})</p>
      `
      : "";
    const hotspots = Array.isArray(data.top_hotspots) ? data.top_hotspots : [];
    const hotspotRows = hotspots.map((h) => `
      <tr>
        <td>${h.kecamatan}</td><td>${h.city}</td>
        <td>${h.predicted_tons} t/day</td><td>${h.trucks_required}</td>
        <td>${h.crews_required}</td><td>${h.man_hours_required}</td>
      </tr>`).join("");
    const hotspotsHtml = hotspotRows ? `
      <h2>Predicted Hotspots &amp; Resource Readiness (Case 2)</h2>
      <table border="1" cellspacing="0" cellpadding="4" style="border-collapse:collapse;font-size:12px;">
        <thead><tr><th>District</th><th>City</th><th>Forecast</th><th>Trucks</th><th>Crews</th><th>Man-hours</th></tr></thead>
        <tbody>${hotspotRows}</tbody>
      </table>` : "";
    const fs = data.fleet_status || {};
    const activityLine = fs.by_activity
      ? Object.entries(fs.by_activity).map(([k, v]) => `${k.replaceAll("_", " ")}: ${v}`).join(" · ")
      : "";
    const fleetHtml = fs.total_trucks
      ? `
      <h2>Fleet Condition (Case 1)</h2>
      <p><b>${fs.total_trucks} units</b> tracked — ${fs.damaged_count} with open damage status.</p>
      <p>Activity: ${activityLine}</p>
      `
      : "";
    const gap = data.facility_summary || {};
    const gapHtml = gap.kecamatan_total
      ? `
      <h2>Facility Gap Analysis (Case 2)</h2>
      <p>${gap.critical_count} critical districts · total gap <b>${gap.total_gap_ton_per_day} t/day</b> ·
      +${gap.total_extra_trucks_needed} trips/day recommended · ${gap.total_new_tps_sites_needed} new TPS sites (bounded share).</p>
      `
      : "";
    const node = document.createElement("section");
    node.className = "pdf-report";
    node.innerHTML = `
      <h1>JWIS Executive Summary</h1>
      <p class="pdf-date">Generated by Jakarta Waste Intelligence System</p>
      <p>${data.summary}</p>
      ${impactHtml}
      ${fleetHtml}
      ${hotspotsHtml}
      ${gapHtml}
      <h2>Audit &amp; Evidence Trail</h2>
      <ul>
        <li>AI route deviation detection (Isolation Forest + corridor geometry) with follow-up trail (OPEN &rarr; DISPATCHED &rarr; RESOLVED)</li>
        <li>Permit-compliant A* rerouting with computed alternative corridors (JORR bypass, coastal toll)</li>
        <li>Prophet+XGBoost forecast over real SILIKA/SIPSN/Open-Meteo data; hotspot rank Spearman 0.998</li>
        <li>Field dispatch loop with driver confirmation and offline sync</li>
      </ul>
      <p style="font-size:11px;color:#666;">${data.model_suitability_note || ""}</p>
    `;
    try {
      const { default: html2pdf } = await import("html2pdf.js");
      await html2pdf()
        .set({
          margin: 12,
          filename: "jwis-executive-summary.pdf",
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: { scale: 2 },
          jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
        })
        .from(node)
        .save();
    } catch {
      const blob = new Blob([data.summary], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = "jwis-executive-summary.txt";
      link.click();
      URL.revokeObjectURL(url);
    }
  }

  return (
    <button 
      className="primary-button" 
      onClick={downloadSummaryPdf} 
      style={{ width: "auto", minHeight: "38px", height: "38px", padding: "0 18px", fontSize: "13px", display: "inline-flex", alignItems: "center", gap: "8px", whiteSpace: "nowrap" }}
    >
      <Download size={15} /> {t("btn_export_pdf")}
    </button>
  );
}
